### ISSUE TITLE
disk_cache permission error

### ISSUE THREAD

**Issue by tenox7** [sarenehan/cache_to_disk#2]
looks like cache_to_disk tries to save cache in the package folder
```
Traceback (most recent call last):
  File "docs-ia.p2h", line 2, in <module>
    from cache_to_disk import cache_to_disk
  File "/usr/local/lib/python3.6/site-packages/cache_to_disk/__init__.py", line 92, in <module>
    ensure_dir(disk_cache_dir)
  File "/usr/local/lib/python3.6/site-packages/cache_to_disk/__init__.py", line 16, in ensure_dir
    os.makedirs(directory)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/cache_to_disk/disk_cache/'
```

could you make it so that the location of the cache can be user specified?

or at least wouldn't it be more portable to store it in system temp folder?

**Comment by buanzo** [comment]
> could you make it so that the location of the cache can be user specified?

I would love this. It could easily be an extra parameter after the days argument when using the decorator, such as:

```
# If cache_path is None it will use the default site-packages one
@cache_to_disk(7, cache_path=USER_CACHE_PATH)
def blahblah(arg):
   ...

```

**Comment by mzpqnxow** [comment]
You _should_  be able to do this (process-wide, at least - not on a per-function basis) by setting the environment variable `DISK_CACHE_DIR`

```
$ export DISK_CACHE_DIR=/tmp/mycache
$ mkdir -p $DISK_CACHE_DIR
$ ./some-app-with-cache-to-file.py
```
